export enum storiesActionTypes {
  INIT = '@@INIT',
  REQUEST_STORIES = 'REQUEST_STORIES',
  REQUEST_STORIES_FAILURE = 'REQUEST_STORIES_FAILURE',
  REQUEST_STORIES_SUCCESS = 'REQUEST_STORIES_SUCCESS',
  REQUEST_STORY = 'REQUEST_STORY',
  REQUEST_STORY_FAILURE = 'REQUEST_STORY_FAILURE',
  REQUEST_STORY_SUCCESS = 'REQUEST_STORY_SUCCESS',
}
